### ISSUE TITLE
Add Windows Application Packaging Project to our build cycle

### ISSUE THREAD

**Issue by skel35** [toggl/toggldesktop#3044]
### 💻 Environment
Platform: Windows

### 📒 Description
[Windows Application Packaging Project](https://docs.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-packaging-dot-net) is currently a recommended way to package Win32 apps to Microsoft Store as it gives the most flexibility and ease of use.

Below is a rough list of things that need to be done in order to make an MS Store release using Win App Packaging Project:

- [x] #3090 Update target .NET Framework version to 4.6.1
- [x] #3057 Install VS 2017 15.5 or newer build tools on the build agent(s) and change the script to use corresponding MSBuild (will also enable us to switch the C++ projects to target newer MSVC Toolset)
- [x] #3090 Add Windows Application Packaging Project to the solution
- [x] #3090 Make sure C++ DLLs are copied to a proper output folder for MS Store build
- [x] #3090 Disable our existing auto-update functionality for MS Store version
- [x] #3090 Make sure MSVC++ redistributable is properly bundled (either that existing method of bundling DLLs works or that dependency on MSVC++ UWP package is set up)
- [x] #3090 Add icons for all necessary sizes
- (Partially done, will reconsider icons after the rebranding) Make icons with a design suited to MS Store applications
- (Moved to #3111) Utilize live tiles to visualize the current state of the timer, remind to track, etc.

### ⭐️ Why do you want this?
The goal is to add Toggl Desktop to Microsoft Store. See #2203.
